server:
  error:
    include-stacktrace: on_param

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-auto: true
  datasource:
    url: 'jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver